export const LOADING = 'LOADING'
export const GRANT_AUTHORITY = 'GRANT_AUTHORITY'
export const SET_TYPE = 'SET_TYPE'
export const OPEN_EDITOR = 'OPEN_EDITOR'
export const CLOSE_EDITOR = 'CLOSE_EDITOR'
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH'
export const SET_USERNAME = 'SET_USERNAME'